### PR TITLE
Block calls with failed verification

### LINKED ISSUE #21: Automatically decline all calls failing STIR/SHAKEN verification
You could try porting the feature from Carrion since we can't have both apps set as the default Caller ID & Spam app
https://github.com/Divested-Mobile/Carrion

### PR DESCRIPTION
**Pull request by papjul**
Fix #21 

Requires Android >= 11 and advanced blocking mode.
Successfully show a blocked call notification when the call fails verification.

However, this won't show in the call logs, because as far as I can see, Android doesn't store this information in call logs.
If we want to show it, we would need to duplicate all calls in a local database table, and have some way to make received calls match with Android system logs. Not a trivial work.

At least the feature is working as intended, so I believe this can be a good first step.

### CODE REVIEW

File: app/src/main/java/fr/vinetos/tranquille/CallScreeningServiceImpl.java [hunk 1]
```diff
@@ -98,8 +99,31 @@ public void onScreenCall(@NonNull Call.Details callDetails) {
...
+                    if (callDetails.getCallerNumberVerificationStatus() ==
+                        Connection.VERIFICATION_STATUS_FAILED
+                    ) {
+                        LOG.trace("onScreenCall() verification failed");
+                        isFailedVerification = true;
+                    }
+                    if (callDetails.getCallerNumberVerificationStatus() ==
+                        Connection.VERIFICATION_STATUS_NOT_VERIFIED
+                    ) {
+                        LOG.trace("onScreenCall() not verified");
```
Comment (papjul) [inline app/src/main/java/fr/vinetos/tranquille/CallScreeningServiceImpl.java:113]: Since you live in France like me, mobile phone numbers always return `NOT_VERIFIED`.
So, to test the feature, you could add `isFailedVerification = true;` here and have someone call you (remember to remove it afterwards).

**Comment by papjul** [comment]
@Vinetos Hi, do you need help with the two PR pending?

If you don't have time to review them at the moment, would it be possible to merge `develop` in `main` and make a new release of what is already ready? So that we can at least have a new release targetting latest Android SDK and getting rid of GreenDAO.
